site_name: pan-os-upgrade Documentation
site_description: Automate upgrades of Palo Alto Networks firewalls with Python
site_url: https://cdot65.github.io/pan-os-upgrade/
repo_name: cdot65/pan-os-upgrade
repo_url: https://github.com/cdot65/pan-os-upgrade
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.instant
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
nav:
  - Home: index.md
  - User Guide:
      - Introduction: user-guide/introduction.md
      - Python Workflow:
          - Getting Started: user-guide/python/getting-started.md
          - Execution: user-guide/python/execution.md
          - Troubleshooting: user-guide/python/troubleshooting.md
      - Docker Workflow:
          - Getting Started: user-guide/docker/getting-started.md
          - Execution: user-guide/docker/execution.md
          - Troubleshooting: user-guide/docker/troubleshooting.md
  - API Reference:
      - pan_os_upgrade: reference/pan_os_upgrade.md
  - About:
      - License: about/license.md
      - Contributing: about/contributing.md
      - Release Notes: about/release-notes.md
extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/termynal.js
  - js/custom.js
