name: Build and push Docker image to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  publish-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the container image
        run: |
          docker build --tag ghcr.io/cdot65/pan-os-upgrade:latest docker
          docker push ghcr.io/cdot65/pan-os-upgrade:latest
